name: Shellcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Syntax Check
        run: bash -n dam.sh
      - name: Run Shellcheck
        run: shellcheck dam.sh
